name: Hotfix Build

on:
  push:
    branches:
    - release-*_hotfixes

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  branch-build:
    # Only run this on repositories in the 'armory-io' org
    if: startsWith(github.repository, 'armory-io/')
    env:
      GRADLE_ARGS: -Partifactory_user=${{secrets.ARTIFACTORY_USER}} -Partifactory_password=${{secrets.ARTIFACTORY_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Java 8 for cross-compilation support. Setting it up before
      # Java 11 means it comes later in $PATH (because of how setup-java works)
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Determine version
        id: build-info
        run: |
          version=$(echo "$(git rev-parse --abbrev-ref HEAD)" | sed 's|release-||' | sed 's|_hotfixes||'))-hotfixes-$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "##[set-output name=version;]$version"
      - name: Build
        run: ./gradlew -Pversion=${{ steps.build-info.outputs.version }} -PenableCrossCompilerPlugin=true build --stacktrace
#      - name: Publish to Artifactory
#        run: ./gradlew $GRADLE_ARGS -Pversion=${{ steps.build-info.outputs.version }} artifactPublish
