name: Integration Tests

on:
  push:
    branches:
      - gha-tests

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  it-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install Java 8 for cross-compilation support. Setting it up before
    # Java 11 means it comes later in $PATH (because of how setup-java works)
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Cache build output
      uses: actions/cache@v2
      with:
        path: '**/build'
        # Saves build outputs for the next commit to use
        key: ${{ runner.os }}-cd-build-${{ github.sha }}
        # Restore build outputs from the previous commit
        restore-keys: |
          ${{ runner.os }}-cd-build-${{ github.event.before }}
    - name: Build
      run: ./gradlew -PenableCrossCompilerPlugin=true build
    # Separating integration tests by provider allows separate logging
    - name: Kubernetes Integration Tests
      run: ./gradlew :clouddriver-kubernetes:integrationTest
